perf: Faster squashfs decompression with zstd
pop-os/iso pull request #289
Opened 2022-03-14 13:30 UTC by mmstick

Decompression is seven times faster than XZ

2022-03-16 14:52 UTC, jackpot51 approved these changes

2022-03-21 23:36 UTC, XV-02 commented
I don't know if it's me mussing something up, but I can build the iso correctly from master, but with this branch I get the following error: 
`mksquashfs: -fstime missing or invalid time value`
at which point the iso fails to finish building.

2022-03-22 02:01 UTC, jackpot51 commented
@mmstick looks like the args are in the wrong order

2022-03-22 04:08 UTC, XV-02 requested changes
With @13r0ck 's eyes for confirmation, the following needs resolution:
```
sudo mksquashfs "$(BUILD)/live" \
		"$(BUILD)/iso/$(CASPER_PATH)/filesystem.squashfs" \
		-noappend -fstime -comp zstd -b 1M -Xcompression-level 22 \
		"$(DISTRO_EPOCH)"
```
Should likely be 
```
sudo mksquashfs "$(BUILD)/live" \
		"$(BUILD)/iso/$(CASPER_PATH)/filesystem.squashfs" \
		-noappend -fstime "$(DISTRO_EPOCH)" \ 
		-comp zstd -b 1M -Xcompression-level 22		
```

`"$(DISTRO_EPOCH)"` needs moving to be associated with `-fstime`

2022-03-22 13:52 UTC, jackpot51 commented
@XV-02 please test install time with a normal debug ISO compared to this.

2022-03-22 17:26 UTC, XV-02 commented
Timing from the point where the user confirms encrypting the disk; install time was 120 seconds with the new compression method, compared with 125 seconds for a control iso.  The "Finishing the Installation" phase was noticably shorter with zstd - 30 seconds compared to 38 for control.

Size on disk for the iso looked to be ~ 0.36 GiB smaller for the zstd iso at compression level 22 - 2.34 GiB compared to 2.7 GiB for control.

2022-03-22 22:03 UTC, XV-02 commented
@jackpot51 So, those numbers are consistent regardless of install media. The system also installs correctly across different hardware. So, I'm happy to move forward with this, assuming nothing else needs specific examination?

2022-03-23 02:10 UTC, merged